// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx5MP3C73rss-9PJyaKYCWgbvmfMChGMo',
    appId: '1:535537539993:web:1b10405b11ded99d0bd108',
    messagingSenderId: '535537539993',
    projectId: 'projetocm-41cb9',
    authDomain: 'projetocm-41cb9.firebaseapp.com',
    databaseURL: 'https://projetocm-41cb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetocm-41cb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwryiFCL7YkfwLOaldZkl4fs981NBkN14',
    appId: '1:535537539993:android:b6bb1aae5ce06bad0bd108',
    messagingSenderId: '535537539993',
    projectId: 'projetocm-41cb9',
    databaseURL: 'https://projetocm-41cb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetocm-41cb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6y6dFriNsUc8PP-n_JKslQvZrk_S7ff8',
    appId: '1:535537539993:ios:2bf72e9db64cc5ea0bd108',
    messagingSenderId: '535537539993',
    projectId: 'projetocm-41cb9',
    databaseURL: 'https://projetocm-41cb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetocm-41cb9.firebasestorage.app',
    iosBundleId: 'com.example.realfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6y6dFriNsUc8PP-n_JKslQvZrk_S7ff8',
    appId: '1:535537539993:ios:2bf72e9db64cc5ea0bd108',
    messagingSenderId: '535537539993',
    projectId: 'projetocm-41cb9',
    databaseURL: 'https://projetocm-41cb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetocm-41cb9.firebasestorage.app',
    iosBundleId: 'com.example.realfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx5MP3C73rss-9PJyaKYCWgbvmfMChGMo',
    appId: '1:535537539993:web:ad1b467079b796840bd108',
    messagingSenderId: '535537539993',
    projectId: 'projetocm-41cb9',
    authDomain: 'projetocm-41cb9.firebaseapp.com',
    databaseURL: 'https://projetocm-41cb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetocm-41cb9.firebasestorage.app',
  );
}
